-- Create Schools Table
CREATE TABLE schools (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  region TEXT NOT NULL,
  country TEXT NOT NULL,
  strength TEXT NOT NULL,
  best_for TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Comparison Factors Table
CREATE TABLE comparison_factors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  factor TEXT NOT NULL,
  asia_value TEXT NOT NULL,
  na_value TEXT NOT NULL,
  icon TEXT NOT NULL,
  display_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Schools
INSERT INTO schools (name, region, country, strength, best_for) VALUES
('HKUST', 'Asia', 'Hong Kong', 'Business, Engineering', 'Students aiming for finance and tech in Asia'),
('HKU', 'Asia', 'Hong Kong', 'Law, Medicine, Liberal Arts', 'Students wanting a global, English-medium experience'),
('NUS', 'Asia', 'Singapore', 'Computer Science, Research', 'Students interested in research and Asia tech'),
('NTU', 'Asia', 'Singapore', 'Engineering, AI', 'Students focused on engineering and innovation'),
('University of Waterloo', 'North America', 'Canada', 'Computer Science, Co-op', 'Students interested in tech jobs and internships'),
('UBC', 'North America', 'Canada', 'Sciences, Sustainability', 'Students who love nature and research'),
('University of Toronto', 'North America', 'Canada', 'Research, AI, Medicine', 'Students wanting a top global research university'),
('McGill', 'North America', 'Canada', 'Medicine, Humanities', 'Students seeking a classic academic experience');

-- Seed Comparison Factors
INSERT INTO comparison_factors (factor, asia_value, na_value, icon, display_order) VALUES
('Tuition', 'Usually lower', 'Usually higher', '💰', 1),
('Career', 'Strong local networks', 'More global tech opportunities', '💼', 2),
('Language', 'English + local language', 'Mainly English', '🗣️', 3),
('Lifestyle', 'Dense cities', 'More campus-based', '🏙️', 4),
('Immigration', 'Usually harder', 'Canada is more friendly', '🍁', 5);
