-- Create Schools Table
CREATE TABLE schools (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  region TEXT NOT NULL,
  country TEXT NOT NULL,
  strength TEXT NOT NULL,
  best_for TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Comparison Factors Table
CREATE TABLE comparison_factors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  factor TEXT NOT NULL,
  asia_value TEXT NOT NULL,
  na_value TEXT NOT NULL,
  icon TEXT NOT NULL,
  display_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Schools
INSERT INTO schools (name, region, country, strength, best_for) VALUES
('HKUST', 'Asia', 'Hong Kong', 'Business, Engineering', 'Students aiming for finance and tech in Asia'),
('HKU', 'Asia', 'Hong Kong', 'Law, Medicine, Liberal Arts', 'Students wanting a global, English-medium experience'),
('NUS', 'Asia', 'Singapore', 'Computer Science, Research', 'Students interested in research and Asia tech'),
('NTU', 'Asia', 'Singapore', 'Engineering, AI', 'Students focused on engineering and innovation'),
('University of Waterloo', 'North America', 'Canada', 'Computer Science, Co-op', 'Students interested in tech jobs and internships'),
('UBC', 'North America', 'Canada', 'Sciences, Sustainability', 'Students who love nature and research'),
('University of Toronto', 'North America', 'Canada', 'Research, AI, Medicine', 'Students wanting a top global research university'),
('McGill', 'North America', 'Canada', 'Medicine, Humanities', 'Students seeking a classic academic experience');

-- Seed Comparison Factors
INSERT INTO comparison_factors (factor, asia_value, na_value, icon, display_order) VALUES
('Tuition', 'Usually lower', 'Usually higher', '💰', 1),
('Career', 'Strong local networks', 'More global tech opportunities', '💼', 2),
('Language', 'English + local language', 'Mainly English', '🗣️', 3),
('Lifestyle', 'Dense cities', 'More campus-based', '🏙️', 4),
('Immigration', 'Usually harder', 'Canada is more friendly', '🍁', 5);

-- Create Student Reviews Table
CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id BIGINT REFERENCES schools(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  major TEXT NOT NULL,
  graduation_year INT,
  rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  review_text TEXT NOT NULL,
  career_outcome TEXT,
  is_approved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: only approved reviews are public
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public reads approved reviews"
  ON reviews FOR SELECT
  USING (is_approved = true OR auth.uid() = user_id);

CREATE POLICY "Authenticated users insert own reviews"
  ON reviews FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Seed sample reviews (requires real user UUIDs — add via Supabase dashboard after creating test accounts)
-- INSERT INTO reviews (school_id, user_id, major, graduation_year, rating, review_text, career_outcome, is_approved)
-- VALUES (1, '<uuid>', 'Computer Science', 2023, 5, 'Amazing research opportunities...', 'Software Engineer at Google', true);
